apiVersion: v2
name: ssh-punchhole
description: Tiny SSH based reverse-tunnel to expose services behind a firewall

home: https://github.com/tamcore/ssh-punchhole

type: application

version: "v0.0.0"

appVersion: "latest"
