{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.metrics.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: {{ include "charts.fullname" . }}
    interval: {{ .Values.metrics.prometheusRule.interval }}
    rules:
    {{- toYaml .Values.metrics.prometheusRule.rules | nindent 4 }}
{{- end }}
