{{- if not $.Values.data.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "charts.fullname" . }}-data
  labels:
  {{- include "charts.labels" . | nindent 4 }}
data:
  id_rsa: {{ required "data.privateKey is required" .Values.data.privateKey | b64enc | quote }}
  known_hosts: {{ required "data.knownHosts is required" .Values.data.knownHosts | b64enc | quote }}
{{- end }}
